services:
  vision_pipeline:
    build: .
    container_name: vision_pipeline

    ports:
      - "8000:8000"

    environment:
      TZ: America/Mexico_City
      YOLO_CONFIG_DIR: /workspace/.ultralytics
    
    volumes:
      - ./outputs:/workspace/outputs
      - ./.ultralytics:/workspace/.ultralytics
      - ./weights:/workspace/weights
    
    stdin_open: true
    tty: true