services:
  vision_pipeline:
    build: .
    container_name: vision_pipeline

    ports:
      - "8000:8000"

    volumes:
      - ./outputs:/workspace/outputs
    
    stdin_open: true
    tty: true