from pathlib import Path
import shutil

def export_prediction(
    generated_image: Path,
    output_root: str,
    output_name: str,
) -> Path:
    """
    Copy the prediction generated by Ultralytics into the
    Vision Pipeline output directory.

    Returns
    -------
    Path: Final location of the exported image.
    """

    destination = Path(output_root) / output_name
    destination.mkdir(parents=True, exist_ok=True)

    if not generated_image.exists():
        raise FileNotFoundError(
            f"Expected output image not found: {generated_image}"
        )

    final_output = destination / generated_image.name

    shutil.copy2(generated_image, final_output) # Or move

    return final_output